import type { Metadata } from "next";
import { Instrument_Serif, DM_Mono } from "next/font/google";

import "./globals.css";
import Footer from '@/components/layout/Footer';


const instrumentSerif = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
});

const dmMono = DM_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrumentSerif.className} ${dmMono.className} antialiased`}
      >
        <div class="flex justify-center items-center flex-col h-full p-6 text-center">
          <div class="w-full h-full max-w-md flex flex-col justify-center items-center gap-10">
            {children}
            
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
